name: Release
on: workflow_dispatch

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install Pulsar
        uses: pulsar-edit/action-pulsar-dependency@v3.2
      - name: Install NPM dependencies
        run: npm ci
      - name: Release
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULSAR_ACCESS_TOKEN: ${{ secrets.PULSAR_ACCESS_TOKEN }}
